spring:
  datasource:
    url: jdbc:postgresql://176.53.162.124:5432/postgres
    username: postgresadmin
    password: Onoq1kbv
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: validate
