spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgresadmin
    password: Onoq1kbv
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

