create table author(
    id int8 generated by default as identity not null,
    fio varchar(2048) not null,
    birthday date,
    email varchar(2048),
    primary key (id));

create table book(
    id int8 generated by default as identity not null,
    name varchar(2048) not null,
    author_id int8 not null,
    description varchar(4096),
    page_count int8,
    primary key (id));

alter table if exists book
    add constraint FKklnrv3weler2ftkweewlky958
    foreign key (author_id) references author;